In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv('/content/survey lung cancer.csv')
data.head()

  GENDER  AGE  SMOKING  ...  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER
0      M   69        1  ...                      2           2          YES
1      M   74        2  ...                      2           2          YES
2      F   59        1  ...                      1           2           NO
3      M   63        2  ...                      2           2           NO
4      F   63        1  ...                      1           1           NO

[5 rows x 16 columns]

In [ ]:
data.tail()

    GENDER  AGE  SMOKING  ...  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER
304      F   56        1  ...                      2           1          YES
305      M   70        2  ...                      1           2          YES
306      M   58        2  ...                      1           2          YES
307      M   67        2  ...                      1           2          YES
308      M   62        1  ...                      2           1          YES

[5 rows x 16 columns]

In [ ]:
data.shape

(309, 16)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [ ]:
data.describe()

              AGE     SMOKING  ...  SWALLOWING DIFFICULTY  CHEST PAIN
count  309.000000  309.000000  ...             309.000000  309.000000
mean    62.673139    1.563107  ...               1.469256    1.556634
std      8.210301    0.496806  ...               0.499863    0.497588
min     21.000000    1.000000  ...               1.000000    1.000000
25%     57.000000    1.000000  ...               1.000000    1.000000
50%     62.000000    2.000000  ...               1.000000    2.000000
75%     69.000000    2.000000  ...               2.000000    2.000000
max     87.000000    2.000000  ...               2.000000    2.000000

[8 rows x 14 columns]

In [ ]:
data.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [ ]:
label_encoder = preprocessing.LabelEncoder()

data['GENDER']= label_encoder.fit_transform(data['GENDER'])

data['GENDER'].unique()

array([1, 0])

In [ ]:
data['LUNG_CANCER']= label_encoder.fit_transform(data['LUNG_CANCER'])

data['LUNG_CANCER'].unique()

array([1, 0])

In [ ]:
data.head(5)

   GENDER  AGE  SMOKING  ...  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER
0       1   69        1  ...                      2           2            1
1       1   74        2  ...                      2           2            1
2       0   59        1  ...                      1           2            0
3       1   63        2  ...                      2           2            0
4       0   63        1  ...                      1           1            0

[5 rows x 16 columns]

In [ ]:
data['LUNG_CANCER'].value_counts()

LUNG_CANCER
1    270
0     39
Name: count, dtype: int64

In [ ]:
data.to_csv('lung_cancer.csv')

In [ ]:
X = data.drop(columns='LUNG_CANCER', axis=1)
Y = data['LUNG_CANCER']
print(X)

     GENDER  AGE  ...  SWALLOWING DIFFICULTY  CHEST PAIN
0         1   69  ...                      2           2
1         1   74  ...                      2           2
2         0   59  ...                      1           2
3         1   63  ...                      2           2
4         0   63  ...                      1           1
..      ...  ...  ...                    ...         ...
304       0   56  ...                      2           1
305       1   70  ...                      1           2
306       1   58  ...                      1           2
307       1   67  ...                      1           2
308       1   62  ...                      2           1

[309 rows x 15 columns]

In [ ]:
print(Y)

0      1
1      1
2      0
3      0
4      0
      ..
304    1
305    1
306    1
307    1
308    1
Name: LUNG_CANCER, Length: 309, dtype: int64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(309, 15) (247, 15) (62, 15)

In [ ]:
model = LinearSVC()

In [ ]:
model.fit(X_train.values, Y_train.values)

LinearSVC()

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearSVC was fitted without feature names
  warnings.warn(

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearSVC was fitted without feature names
  warnings.warn(

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Training data :  0.9311740890688259
Accuracy on Test data :  0.9032258064516129

In [ ]:
input_data = (1,61,2,1,1,1,2,2,1,1,1,1,2,1,1)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Lung Cancer')
else:
  print('The Person has Lung Cancer')

[1]
The Person has Lung Cancer

In [ ]:
import pickle

In [ ]:
filename='lungcancer_model.sav'
pickle.dump(model,open(filename,'wb'))
loaded_model=pickle.load(open('lungcancer_model.sav','rb'))

In [ ]:
for column in X_train.columns:
  print(column)

GENDER
AGE
SMOKING
YELLOW_FINGERS
ANXIETY
PEER_PRESSURE
CHRONIC DISEASE
FATIGUE
ALLERGY
WHEEZING
ALCOHOL CONSUMING
COUGHING
SHORTNESS OF BREATH
SWALLOWING DIFFICULTY
CHEST PAIN